steps:
  # Step to check environment and potentially delete service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if required environment variables are set
        if [[ -z "$_TARGET_PROJECT_ID" || -z "$_SERVICE_NAME" || -z "$_REGION" || -z "$_ENVIRONMENT" ]]; then
          echo "Error: TARGET_PROJECT_ID, SERVICE_NAME, REGION, and ENVIRONMENT must be provided."
          exit 1
        fi

        echo "Checking environment..."

        if [[ "$_ENVIRONMENT" == "prod" ]]; then
          echo "Approval required for production environment."
          exit 0  # Stop the pipeline for approval
        fi

        echo "Deleting Cloud Run service: $_SERVICE_NAME in $_REGION for environment: $_ENVIRONMENT in project: $_TARGET_PROJECT_ID..."

        # Delete Cloud Run service from the specified project and environment
        if gcloud run services delete "$_SERVICE_NAME" \
          --platform managed \
          --region "$_REGION" \
          --project "$_TARGET_PROJECT_ID" \
          --quiet; then
          echo "Successfully deleted Cloud Run service: $_SERVICE_NAME."
        else
          echo "Error: Failed to delete Cloud Run service: $_SERVICE_NAME"
          exit 1  # Fail the build if deletion fails
        fi

  # Conditional Approval Step
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$_ENVIRONMENT" == "prod" ]]; then
          echo "Approval stage for production environment. Please approve to continue."
          # Placeholder for approval logic; you could integrate with an external approval system or manual process.
          exit 0  # Pause for approval
        fi

  # Step to delete Cloud Run service after approval
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$_ENVIRONMENT" == "prod" ]]; then
          echo "Continuing to delete Cloud Run service: $_SERVICE_NAME in $_REGION for environment: $_ENVIRONMENT in project: $_TARGET_PROJECT_ID..."

          # Delete Cloud Run service from the specified project and environment
          if gcloud run services delete "$_SERVICE_NAME" \
            --platform managed \
            --region "$_REGION" \
            --project "$_TARGET_PROJECT_ID" \
            --quiet; then
            echo "Successfully deleted Cloud Run service: $_SERVICE_NAME from project: $_TARGET_PROJECT_ID."
          else
            echo "Error: Failed to delete Cloud Run service: $_SERVICE_NAME"
            exit 1  # Fail the build if deletion fails
          fi
        else
          echo "Successfully deleted Cloud Run service: $_SERVICE_NAME from project: $_TARGET_PROJECT_ID. No further action needed for non-production environments."
        fi

substitutions:
  _TARGET_PROJECT_ID: ''
  _SERVICE_NAME: ''
  _REGION: ''
  _ENVIRONMENT: ''
timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY
